title: Happy Home & Living
description: Home Decor, Fashion, Gardening & Parenting Blog

url: "https://syedismail94.github.io"
baseurl: "/keywordsfromurls"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default

markdown: kramdown

# Clean URLs (NO dates)
permalink: /:categories/:title/

# Disable sidebar globally
sidebar:
  nav: false

# Footer links
footer:
  links:
    - label: "About Us"
      url: /about/
    - label: "Contact Us"
      url: /contact/
    - label: "Privacy Policy"
      url: /privacy-policy/
    - label: "Disclaimer"
      url: /disclaimer/

# Custom CSS
custom_css:
  - assets/css/custom.css
