title: Keywords From URLs
description: Home Decor, Fashion, Gardening & Parenting Blog

url: "https://syedismail94.github.io"
baseurl: "/keywordsfromurls"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default

markdown: kramdown
permalink: /:categories/:title/

# Footer links (About / Contact / Privacy)
footer:
  links:
    - label: "About Us"
      url: /about/
    - label: "Contact Us"
      url: /contact/
    - label: "Privacy Policy"
      url: /privacy-policy/
    - label: "Disclaimer"
      url: /disclaimer/

